let content={};
const saved=localStorage.getItem('sillinkContent');
fetch('content.json').then(r=>r.json()).then(base=>{content=saved?JSON.parse(saved):base; render();}).catch(()=>{content=saved?JSON.parse(saved):{};render();});
function render(){document.querySelectorAll('[data-content]').forEach(el=>{const k=el.dataset.content;if(content[k]!==undefined){el.textContent=content[k];if(k==='email'&&el.tagName==='A')el.href='mailto:'+content[k];}});document.title=(content.brand||'Sillink Groupd')+' | Linking Industries. Powering Progress.';if(content.theme)Object.entries(content.theme).forEach(([k,v])=>document.documentElement.style.setProperty('--'+k,v));
const bg=document.getElementById('businessGrid');if(bg)bg.innerHTML=(content.businesses||[]).map(b=>`<article class="business"><span>${b[0]}</span><h3>${esc(b[1])}</h3><p>${esc(b[2])}</p><a href="#contact">Explore sector <b>↗</b></a></article>`).join('');
const wg=document.getElementById('whyGrid');if(wg)wg.innerHTML=(content.why||[]).map((w,i)=>`<article><span>0${i+1}</span><h3>${esc(w[0])}</h3><p>${esc(w[1])}</p></article>`).join('');
const fb=document.getElementById('footerBusinesses');if(fb)fb.innerHTML=(content.businesses||[]).slice(0,10).map(b=>`<a href="#businesses">${esc(b[1])}</a>`).join('');
const title=document.querySelector('.hero h1');if(title&&content.heroTitle)title.innerHTML=esc(content.heroTitle.split('\\n')[0])+'<br><em>'+esc(content.heroTitle.split('\\n')[1]||'')+'</em>';}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('nav').classList.toggle('open'));
document.getElementById('contactForm')?.addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('formStatus');const btn=e.target.querySelector('button');status.textContent='Sending…';btn.disabled=true;try{const r=await fetch('/api/contact.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to send');status.textContent='Thank you. Your message has been sent.';e.target.reset();}catch(err){status.textContent=err.message+' Please email '+(content.email||'inspireiqglobal@gmail.com')+' directly.';}finally{btn.disabled=false;}});
